name: Functional Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      MAVEN_OPTS: "-Xss8M -Xmx8G"
      ENABLE_SSH: "true"
      SSH_BASE_DIR: ${{ vars.RPI_BASEDIR }}
      SSH_HOST: ${{ vars.RPI_HOST }}
      SSH_PORT: ${{ vars.RPI_PORT }}
      SSH_USERNAME: ${{ vars.RPI_USERNAME }}
      SSH_PASSWORD: ${{ secrets.RPI_PASSWORD }}
      TESTCASE_DIR: "testcases/custom;testcases/functional;testcases/h_functional"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Install LLVM and Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential llvm clang openssh-server

      - name: Install Dependencies and Build
        run: |
          mvn clean install -DskipTests -B
      

      - name: Run ARM Tests
        run: |
          timeout 20m mvn clean test -Dchill.ci=true -Dchill.runner=SSHARM64ASMRunner

      - name: Upload JUnit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/
