name: ARM Functional Test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      MAVEN_OPTS: "-Xss8M"
      TESTCASE_DIR: "testcases/functional;testcases/h_functional"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17

      - name: Install Maven Dependencies
        run: |
          mvn dependency:go-offline -q
          mvn dependency:resolve-plugins -q
          mvn dependency:resolve -DincludeTypes=test-jar -q
          mvn clean install -DskipTests -q

      - name: Run Tests
        id: run-tests
        continue-on-error: true
        run: |
          timeout 6m mvn clean test

      - name: Upload JUnit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/
