name: ARM Functional Test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      MAVEN_OPTS: "-Xss8M"
      TESTCASE_DIR: "testcases/functional;testcases/h_functional"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install LLVM and Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential llvm clang

      - name: Install Dependencies and Build
        run: |
          mvn clean install -DskipTests -B

      - name: Run Tests
        id: run-tests
        continue-on-error: true
        run: |
          timeout 20m mvn clean test

      - name: Upload JUnit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/
