name: ARM Functional Test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xss8M"
      TESTCASE_DIR: "testcases/functional;testcases/h_functional"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        
      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install Maven Dependencies
        run: |
          nix-shell --run "mvn dependency:go-offline -q"
          nix-shell --run "mvn clean install -DskipTests -q"

      - name: Run Tests
        run: |
          nix-shell --run "mvn clean test"

      - name: Upload JUnit test reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/
